### ISSUE TITLE
"import bsddb" deprecated since Python 2.6; move to bsddb3?

### ISSUE THREAD

**Issue by hartwork** [dozzie/yumbootstrap#10]
Hi!

I noticed `import bsddb` in the current code which happens to trigger a bug in my environment.
The bsddb module is [deprecated since Python 2.6 and has been removed in Python 3](https://docs.python.org/2/library/bsddb.html); is a move to [bsddb3](https://www.jcea.es/programacion/pybsddb.htm) an option to you?

I did
```
sed 's,^import bsddb$,import bsddb3 as bsddb,' -i lib/yumbootstrap/bdb.py
```
and it seems to work so the transition could be easy.

Best, Sebastian

**Comment by dozzie** [comment]
Historically, yumbootstrap needed to run on Python 2.3 from Red Hat 4.
I no longer work with Red Hats, so this stopped being an issue, but I never
had plans to use Python 3, so I would rather keep backward compatibility.
