### ISSUE TITLE
Publish official RPMs, DEBs for yumbootstrap

### ISSUE THREAD

**Issue by mcandre** [dozzie/yumbootstrap#12]
As a newbie, I want to be able to install yumbootstrap via yum/apt-get, to make it easier to setup.

**Comment by dozzie** [comment]
I don't intend to make such big obligation as to run my own public
APT and Yum repositories.

Also, if you need chroot installation, it's hard to claim you're newbie. You
can handle instructions that have merely two or three simple steps.

**Comment by mcandre** [comment]
> I don't intend to make such big obligation as to run my own public
APT and Yum repositories.

Understood. You only have so much time to spare.

> Also, if you need chroot installation, it's hard to claim you're newbie. You
can handle instructions that have merely two or three simple steps.

Newbie's relative, heh.
