### ISSUE TITLE
Use python2 hashbangs instead of "python" in scripts

### ISSUE THREAD

**Issue by prg318** [dozzie/yumbootstrap#22]
Yumbootstrap works well on Arch Linux and I have created an Arch package:  https://aur.archlinux.org/packages/yumbootstrap-git/

I'm required to replace the "#!/usr/bin/python" hashbangs with "#!/usr/bin/python2" in order to exist on a modern python3 system.  Since yumbootstrap requries python2, its best to use a "python2" hashbang for systems with both versions of python installed.  An even better hashbang would be "#!/usr/bin/env python2" to allow for python2 installations that are installed in a non-standard directory.

Thanks again for your work on this very useful tool!  It works very well with the "arch-chroot" script from the arch install scripts.

Edit:  I had to change setup.py, bin/yumbootstrap and distros/scripts/*.py

**Comment by dozzie** [comment]
I'm not interested in dancing to the tune Arch plays alone. I refuse to watch out for warts caused by only one distribution that I don't even use.
