### ISSUE TITLE
Issue Building Centos7 on ubuntu

### ISSUE THREAD

**Issue by zohaibtechknox** [dozzie/yumbootstrap#25]
I am creating a centos7 image with yumbootstrap method  on a ubuntu 14.04 and when i try to run this image as kvm i am getting this issue 
`Failed to mount sysroot`
`Dependency failed for Intird Root File System`
So debug this issue step by step and found that during bootstrap procedure yumbootstrap copy contents of  /proc/self/mounts and /etcmtab of ubuntu and copy those file in centos7 rootfile system and FYI centos7 using xfx file sysytem and ubuntu is using ext3. I have try to replace these files but i am unable to do that becuase these files are readonly even for root user.

**Comment by dozzie** [comment]
Freshly prepared chroot in its raw state is rarely suitable for running as a standalone, no matter how it was prepared (yumbootstrap, debootstrap, or something else) and usually needs some postprocessing, so it's not a big surprise.

yumbootstrap shouldn't copy `/proc/self/mounts` anywhere and only creates *empty* `$TARGET/etc/mtab` (and empty `$TARGET/etc/fstab`), and then, `/etc/mtab` shouldn't cause any problems for booting, even with invalid content.

Care to provide more details about your environment? Are you running custom postprocessing or postinstall scripts?

**Comment by zohaibtechknox** [comment]
Ok let me explain my scenario in detail below are commands and script I have used to create a centos-7 image  3rd step is the problem i want to change /etc/mtab here but unable to do it ..

- sudo mkdir -p /tmp/centos
- /usr/sbin/yumbootstrap --verbose centos-7 /tmp/centos
- I want to change /etc/mtab here becuase I think ubuntu useing ext3 and centos7 using xfs file system is creating problem for me.. 
- sudo mount proc  /tmp/centos/proc -t proc
- sudo mount sysfs /tmp/centos/sys -t sysfs
- Installation scripts installing yum packages , configurations etc
-  create-users
- sudo bash -c 'tar cf - . | sudo pigz > /tmp/centos.tar.gz'

here i am attaching  error message file  which I  am getting while running this as kvm virtual machine 

![sysroot](https://cloud.githubusercontent.com/assets/7113853/22640199/6bfa47d2-ec73-11e6-8624-d3bcd8653f7e.png)

**Comment by dozzie** [comment]
Either the procedure you provided is incomplete (lacks the most important part) or you're trying to run a tarball as a disk image. If it is the latter, it won't work; you need a disk image.

**Comment by zohaibtechknox** [comment]
I have mention in ist post that I am creating qcow2 image from tarball . for this here is my process
cp ~/centos.dcso.tar.gz /tmp
./define-domain.sh mincentos 1024 1 # it is a script which will create centos.xml file for domain defination
sudo qemu-img create -f raw /tmp/centos 30G
sudo mkfs.ext3 -F /tmp/centos
sudo mount -o loop /tmp/centos /mnt
sudo tar -C /mnt -zxf /tmp/centos.dcso.tar.gz
sudo umount /mnt
sudo qemu-img convert -O qcow2 /tmp/centos /var/lib/libvirt/images/centos.qcow2
virsh start centos
