### ISSUE TITLE
build fedora failed.

### ISSUE THREAD

**Issue by Whishay** [dozzie/yumbootstrap#33]
I have successfully built CendOS 6, thanks a lot.

It broke when I was intending to build a Fedora 22, initially I found the url in 'fedora.suited' was not available anymore, after set it the workable archive, it failed as below, I am not sure if this is caused by
Fedora has put all packages to alphabetically ordered directory instead of put them all together as CentOS does, does anyone know this?

Workable URL:
http://archives.fedoraproject.org/pub/archive/fedora/linux/releases/22/Everything/x86_64/os/Packages/

Error message:
Unable to detect release version (use '--releasever' to specify release version)
No match for argument: coreutils
No match for argument: bash
No match for argument: grep
No match for argument: gawk
No match for argument: basesystem
No match for argument: rpm
No match for argument: initscripts
No match for argument: iproute
No match for argument: openssh-server
No match for argument: less
No match for argument: make
No match for argument: mktemp
No match for argument: vim-minimal
No match for argument: yum
No match for argument: chkconfig
No match for argument: plymouth
No match for argument: rootfiles
No match for argument: fedora-release
No match for argument: /usr/bin/db_load
Error: Unable to find a match

**Comment by dozzie** [comment]
I have no idea what you did. This is the first time I've ever seen such a message. Maybe you pointed the repository to a listing of a directory with packages instead of root URL for the repository, where the metadata resides?
