### ISSUE TITLE
bootstrap centos-7 fails with an error:

### ISSUE THREAD

**Issue by usrleon** [dozzie/yumbootstrap#35]
yumbootstrap centos-7 ./centos7
After all packages installed I'm getting this error and after that yum and rpm are broken
...

> Complete!
> error: Failed to initialize NSS library
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/usr/lib64/python2.7/site-packages/rpm/__init__.py", line 10, in <module>
>     from rpm.transaction import *
>   File "/usr/lib64/python2.7/site-packages/rpm/transaction.py", line 5, in <module>
>     from rpm._rpm import ts as TransactionSetCore
> ImportError: cannot import name ts
> Traceback (most recent call last):
>   File "/etc/yumbootstrap/suites/scripts/fix_rpmdb.py", line 27, in <module>
>     yum.fix_rpmdb()
>   File "/usr/lib/pymodules/python2.7/yumbootstrap/yum.py", line 157, in fix_rpmdb
>     env = self.yum_conf.env,
>   File "/usr/lib/pymodules/python2.7/yumbootstrap/sh.py", line 90, in run
>     check_error(command[0], proc.returncode)
>   File "/usr/lib/pymodules/python2.7/yumbootstrap/sh.py", line 16, in check_error
>     raise YBError('"%s" exited with code %d', cmd, code, exit = 1)
> yumbootstrap.exceptions.YBError: "python" exited with code 1

Here is RH7 issue which looks exactly the same https://access.redhat.com/solutions/3134931

**Comment by usrleon** [comment]
The issue is there is no /dev/urandom in chroot which is required by one of rpm dependent libs
open("/dev/urandom", O_RDONLY)          = -1 ENOENT (No such file or directory)
open("/dev/urandom", O_RDONLY)          = -1 ENOENT (No such file or directory)
open("/proc/sys/crypto/fips_enabled", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, "error: ", 7error: )                  = 7
write(2, "Failed to initialize NSS library"..., 33Failed to initialize NSS library

**Comment by rgooch** [comment]
Would you accept a PR which adds a post-install script which creates this device node (and maybe `/dev/null` and `/dev/zero` as well)?

**Comment by dozzie** [comment]
@usrleon: good catch with `strace`. I had a vague memory of some RPM providing the necessary device files, but I can't find anything, and CentOS 6 from the provided suites doesn't create them either.

@rgooch: I would, but this time the fix was small, so I implemented it myself. Sorry ;)

18f9f50
