### ISSUE TITLE
Unable to install under Centos 7

### ISSUE THREAD

**Issue by chrisplusplus** [dozzie/yumbootstrap#40]
Can anyone get this to install under centos 7?  I can't for the life of me get this to work.

**Comment by dozzie** [comment]
I'm told people do. I also just checked, building and installing works fine.

**Comment by chrisplusplus** [comment]
I actually did figure it out.  For Centos 7:
make srpm
rpmbuild --rebuild yumbootstrap-*.src.rpm
cd /root/rpmbuild/RPMS
rpm -i [name-of-package.noarch.rpm]
