### ISSUE TITLE
add new distribution

### ISSUE THREAD

**Issue by amidevous** [dozzie/yumbootstrap#43]
please rapid add centos 8

fedora 23, 24, 25, 26, 27,  28, 29, 30, 31 and 32

it is very important that the distribution list is kept up to date

without this your project has practically no use a by centos 6 and 7 all the other distribution you provide are obsolete

**Comment by dozzie** [comment]
When I was writing _yumbootstrap_, I made a special effort to describe how to add a custom distribution and make it as simple as possible. As such, I'm perfectly fine with _yumbootstrap_ becoming useless to somebody who never put any work in this by themselves, thank you very much.
