### ISSUE TITLE
Support for Fedora 21?

### ISSUE THREAD

**Issue by hartwork** [dozzie/yumbootstrap#6]
Hi!

Fedora 21 does not seem to be supported. Are there plans to add support for it?

Best, Sebastian

**Comment by mcandre** [comment]
+1 Please add scripts for building fedora-21 and fedora-22

**Comment by dozzie** [comment]
> Fedora 21 does not seem to be supported. Are there plans to add support for it?

I no longer have plans for yumbootstrap, as I lost my main use case for it
when changing jobs.

On the other hand, I anticipated this and made it simple to prepare suites
based on previous OS releases, so you didn't need to sit on your hands waiting
for me to update. Suites for Fedora 21 and 22 added.

**Comment by hartwork** [comment]
For the record, the commit is 7ad2aec7b1ae454c3d744de93d1022c33b04e4de.
