### ISSUE TITLE
Installation of fedora-20 fails with "Error: xz compression not available" ?

### ISSUE THREAD

**Issue by hartwork** [dozzie/yumbootstrap#9]
```
# sudo /usr/sbin/yumbootstrap fedora-20 /var/tmp/fedora-20
fedora
fedora-updates
(1/2): fedora-updates/primary_db
(2/2): fedora/primary_db
Error: xz compression not available
"/usr/bin/yum" exited with code 1
```
Is there anything I can do?

**Comment by dozzie** [comment]
Honestly, I don't know. I have no idea how to reproduce this, much less how to
fix it.

You may try install Fedora 19 chroot first, install yumbootstrap there and
install Fedora 20 under that chroot. I know it's merely a workaround, but it
should work.

**Comment by hartwork** [comment]
I had a look at yum code by now. In `yum/misc.py` it reads
```
_available_compression = ['gz', 'bz2']
try:
    import lzma
    _available_compression.append('xz')
except ImportError:
    lzma = None
```
and
```
    if ztype not in _available_compression:
        msg = "%s compression not available" % ztype
        raise Errors.MiscError, msg
```
further down. Installing [pyliblzma](http://pypi.python.org/pypi/pyliblzma) fixed this very problem. My system's yum was missing a dependency on that. Fixed that now.

**Comment by kergoth** [comment]
Thanks for that info, I had to install python-lzma on my ubuntu machine to resolve this as well. Should probably add an FAQ for this.
